#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 18 21:47:44 2024

@author: kayab
"""



import subprocess
import pyperclip
import random



file = open('draculaflow/bars.txt')
bars = file.readlines()

bar = random.choice(bars)

pyperclip.copy(bar)
pyperclip.paste()